apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: legacy-shopify-app-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: legacy-shopify-app-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: secret/skirmshop/legacy-shopify-app
