apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: skirmshop

resources:
  - externalsecret.yaml
  - manifest.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: skirmshop
      app.kubernetes.io/managed-by: gitops
      e-dani.com/activation: disabled
