apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: product-weight-rate-limit
spec:
  rateLimit:
    average: 30
    burst: 10
    period: 1m
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: product-weight-api
spec:
  entryPoints:
    - websecure
  ingressClassName: traefik-edge
  routes:
    - kind: Rule
      match: Host(`skirmshop.e-dani.com`) && PathPrefix(`/api/product-weight`)
      middlewares:
        - name: rag-product-weight-rate-limit
      services:
        - name: rag-app
          port: 80
  tls:
    store:
      name: default
      namespace: traefik-edge
